spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.174.107:3306/gotest
    username: hcy
    password: hcy
  servlet:
    multipart:
      max-file-size: 20MB
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.web.HttpLogging : debug


server:
  tomcat:
    basedir: /www/uploadtask/tmp
